import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import VocabCardList from "../components/VocabCardList";
import CategoryCardList from "../components/CategoryCardList";
import { styled } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StTitle>Taiwanese Hokkien Vocab</StTitle>
        <CategoryCardList />
        <VocabCardList spreadsheetUrl={spreadsheetURL} categoryName="colors" />
      </main>
    </>
  );
}

const spreadsheetURL =
  "https://docs.google.com/spreadsheets/d/e/2PACX-1vSf2CHodZ6hYigjqYwqdIY8p_ZsJI5LFUTYhhie-69E4bkTBjpUXkhoYox5_4CDW3WEZEmN4xhECfpF/pubhtml?gid=70370957&single=true";

const StTitle = styled.h1`
  margin: 8px;
  text-align: center;
`;
